apiVersion: v1
kind: Service
metadata:
  name: assignment-frontend-service
spec:
  type: {{ .Values.fe.svcType }}
  ports:
    - targetPort: 4200
      port: 4200
  selector: {{ include "common.feLabels" . | nindent 4 }}
