apiVersion: v1
kind: Service
metadata:
  name: assignment-backend-service
spec:
  type: {{ .Values.be.svcType }}
  ports:
    - targetPort: 3000
      port: 3000
  selector: {{ include "common.beLabels" . | nindent 4 }}
